version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
Check-in the config and see it run. You can see the output of the job in the CircleCI app.

